Update 67-stop_me_if_you_can

diff --git a/0x05-processes_and_signals/67-stop_me_if_you_can b/0x05-processes_and_signals/67-stop_me_if_you_can
--- a/0x05-processes_and_signals/67-stop_me_if_you_can
+++ b/0x05-processes_and_signals/67-stop_me_if_you_can
@@ -1,4 +1,11 @@
 #!/usr/bin/env bash
-# A Bash script that sends a SIGTERM to the 7-highlander process
+# This script sends the SIGTERM signal to the 7-highlander process
 
+# pkill -f sends SIGTERM (signal 15) to all processes matching the full command line.
 pkill -f 7-highlander
+
+# Check the exit status of the pkill command
+if [ $? -eq 0 ]; then
+    # Output the required success message
+    echo "OK"
+fi
